version: "3.9"

services:
  postgres:
    image: postgres:17

    container_name: educacional

    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5430:5432"

    volumes:
      - ./postgres_data:/var/lib/postgresql/data